# Generated by Django 5.0.2 on 2024-03-05 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '__first__'),
        ('member', '__first__'),
        ('selleaf', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('apply_status', models.IntegerField(choices=[(0, '신청 완료'), (-1, '신청 취소'), (1, '수업 완료')], default=0)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selleaf.date')),
                ('kit', models.ForeignKey(default='offline', on_delete=django.db.models.deletion.PROTECT, to='lecture.kit')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecture.lecture')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='selleaf.time')),
            ],
            options={
                'db_table': 'tbl_apply',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trainee_name', models.CharField(max_length=100)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apply.apply')),
            ],
            options={
                'db_table': 'tbl_trainees',
                'ordering': ['-id'],
            },
        ),
    ]
