# Generated by Django 5.0.2 on 2024-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_alter_apply_date_alter_apply_kit_alter_apply_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
