# Generated by Django 5.0.2 on 2024-03-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_status',
            field=models.BooleanField(default=False),
        ),
    ]
