# Generated by Django 5.0.2 on 2024-03-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
