# Generated by Django 5.0.2 on 2024-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postreplylike',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postscrap',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
