# Generated by Django 5.0.2 on 2024-03-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postcategory_post_alter_postscrap_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttag',
            options={},
        ),
    ]
