# Generated by Django 5.0.2 on 2024-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_post_post_content_alter_post_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_content",
            field=models.CharField(max_length=8000),
        ),
    ]
