# Generated by Django 5.0.2 on 2024-05-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_post_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postreply",
            name="post_reply_status",
        ),
    ]
