# Generated by Django 5.0.2 on 2024-03-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lectureplacefile',
            table='tbl_lecture_place_file',
        ),
    ]
