# Generated by Django 5.0.2 on 2024-03-08 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_remove_lecture_date_remove_lecture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturescrap',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LectureAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address_zipcode', models.CharField(max_length=60, null=True)),
                ('address_city', models.CharField(max_length=255)),
                ('address_district', models.CharField(max_length=255)),
                ('address_detail', models.CharField(max_length=255)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecture.lecture')),
            ],
            options={
                'db_table': 'tbl_lecture_address',
            },
        ),
    ]
