# Generated by Django 5.0.2 on 2024-03-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_alter_lecturescrap_status_lectureaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
