# Generated by Django 5.0.2 on 2024-03-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_lecture_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureaddress',
            name='address_detail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
