# Generated by Django 5.0.2 on 2024-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='target_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
