# Generated by Django 5.0.2 on 2024-03-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_alarm_target_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ['-id']},
        ),
    ]
