# Generated by Django 5.0.2 on 2024-03-05 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_trade_category',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trade_price', models.IntegerField(default=0)),
                ('trade_title', models.CharField(max_length=80)),
                ('trade_content', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('kakao_talk_url', models.CharField(max_length=500)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('trade_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.tradecategory')),
            ],
            options={
                'db_table': 'tbl_trade',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_url', models.ImageField(upload_to='file/%Y/%m/%d')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.trade')),
            ],
            options={
                'db_table': 'tbl_trade_file',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TradePlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant_name', models.CharField(max_length=50)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.trade')),
            ],
            options={
                'db_table': 'tbl_trade_plant',
            },
        ),
        migrations.CreateModel(
            name='TradeScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.trade')),
            ],
            options={
                'db_table': 'tbl_trade_scrap',
                'ordering': ['-id'],
            },
        ),
    ]
