# Generated by Django 5.0.2 on 2024-03-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_kakao_talk_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='kakao_talk_url',
        ),
    ]
