# Generated by Django 5.0.2 on 2024-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_tradescrap_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradescrap',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
