# Generated by Django 5.0.2 on 2024-03-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_trade_kakao_talk_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='kakao_talk_url',
        ),
    ]
