# Generated by Django 5.0.2 on 2024-03-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_remove_trade_kakao_talk_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='kakao_talk_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
