# Generated by Django 5.0.2 on 2024-03-14 10:19

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_alter_memberaddress_address_detail'),
        ('trade', '0003_alter_tradescrap_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_content', models.CharField(max_length=50)),
                ('report_status', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trade.trade')),
            ],
            options={
                'db_table': 'tbl_trade_report',
                'ordering': ['-id'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
