# Generated by Django 5.0.2 on 2024-03-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='member_id',
            new_name='member',
        ),
    ]
