# Generated by Django 5.0.2 on 2024-03-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_member_id_report_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_name',
        ),
    ]
