# Generated by Django 5.0.2 on 2024-03-14 19:27

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_alter_lectureaddress_address_detail'),
        ('member', '0003_member_admin_type'),
        ('report', '0002_knowhowreplyreport_knowhowreport_postreplyreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_content', models.CharField(max_length=50)),
                ('report_status', models.BooleanField(default=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecture.lecture')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_lecture_report',
                'ordering': ['-id'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
