# Generated by Django 5.0.2 on 2024-03-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaddress',
            name='address_zipcode',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
