# Generated by Django 5.0.2 on 2024-03-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaddress',
            name='address_name',
            field=models.CharField(default='가입 주소', max_length=255),
        ),
    ]
