# Generated by Django 5.0.2 on 2024-03-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaddress',
            name='address_detail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]