# Generated by Django 5.0.2 on 2024-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_memberaddress_address_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='admin_type',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="member",
            name="member_knowhow_ai_model",
        ),
    ]