# Generated by Django 5.0.2 on 2024-05-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_member_admin_type"),
    ]

    operations = [

    ]
