# Generated by Django 5.0.2 on 2024-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0005_member_member_knowhow_ai_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_knowhow_ai_model",
            field=models.TextField(default="base"),
        ),
    ]
