# Generated by Django 5.0.2 on 2024-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='kit',
            field=models.CharField(default='offline', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
