# Generated by Django 5.0.2 on 2024-03-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('lecture', '0002_alter_lectureplacefile_table'),
        ('selleaf', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='selleaf.date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='kit',
            field=models.ForeignKey(default='offline', on_delete=django.db.models.deletion.PROTECT, to='lecture.kit'),
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='selleaf.time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
