# Generated by Django 5.0.2 on 2024-03-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowhow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowhow',
            name='knowhow_status',
        ),
        migrations.AddField(
            model_name='knowhowlike',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowhowreplylike',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowhowscrap',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
