# Generated by Django 5.0.2 on 2024-03-04 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowhow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowhowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_knowhow_category',
            },
        ),
    ]
