# Generated by Django 5.0.2 on 2024-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowhow', '0002_remove_knowhow_knowhow_status_knowhowlike_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowhowscrap',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
