# Generated by Django 5.0.2 on 2024-05-17 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowhow', '0003_alter_knowhowscrap_status'),
        ('member', '0004_memberaifile'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowhowView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('knowhow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowhow.knowhow')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_knowhow_view',
            },
        ),
    ]
