# Generated by Django 5.0.2 on 2024-05-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowhow', '0004_knowhowview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowhow',
            name='knowhow_content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='knowhow',
            name='knowhow_title',
            field=models.CharField(max_length=80),
        ),
    ]
