# Generated by Django 5.0.2 on 2024-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowhow", "0005_alter_knowhow_knowhow_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowhow",
            name="knowhow_content",
            field=models.CharField(max_length=8000),
        ),
    ]
