# Generated by Django 5.0.2 on 2024-05-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiPostReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=1000)),
                ("target", models.SmallIntegerField(default=0)),
            ],
            options={
                "db_table": "tbl_ai_post_reply",
                "ordering": ["-id"],
            },
        ),
    ]
