# Generated by Django 5.0.2 on 2024-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiKnowhow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knowhow_title", models.CharField(max_length=80)),
                ("knowhow_content", models.CharField(max_length=8000)),
                ("knowhow_category", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tbl_ai_knowhow",
            },
        ),
        migrations.CreateModel(
            name="AiPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=80)),
                ("post_content", models.CharField(max_length=8000)),
                ("post_tags", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "tbl_ai_post",
            },
        ),
        migrations.CreateModel(
            name="AiPostReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=10000)),
                ("target", models.SmallIntegerField(default=0)),
            ],
            options={
                "db_table": "tbl_ai_post_reply",
                "ordering": ["-id"],
            },
        ),
    ]
