# Generated by Django 5.0.2 on 2024-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiKnowhow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knowhow_title", models.CharField(max_length=80)),
                ("knowhow_content", models.CharField(max_length=8000)),
                ("knowhow_category", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tbl_ai_knowhow",
            },
        ),
        migrations.CreateModel(
            name="AiPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=80)),
                ("post_content", models.CharField(max_length=8000)),
                ("post_tags", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tbl_ai_post",
            },
        ),
    ]
