# Generated by Django 5.0.2 on 2024-05-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_alter_aipostreply_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aipost",
            name="post_tags",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
