# Generated by Django 5.0.2 on 2024-03-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_alter_apply_apply_status'),
        ('order', '0002_remove_order_order_status_order_member_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='time',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='apply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='apply.apply'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.order'),
            preserve_default=False,
        ),
    ]
